---
language: python
python:
  - "2.7"
env:
  - TEST=00-syntax
  - TEST=01-defaults
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq realpath
 - sudo apt-get install -qq python-apt python-pycurl
install:
  - pip install ansible
  - ansible --version
script:
  - echo  localhost > inventory
  - echo  "[defaults]"                             >  ansible.cfg
  - echo  "hostfile = ./inventory"                 >> ansible.cfg
  - echo  "roles_path = $(dirname $(realpath .))"  >> ansible.cfg
  - echo  "remote_user = root"                     >> ansible.cfg
  - echo  "transport = local"                      >> ansible.cfg
#  - echo  "vars_files:"                            >> ansible.cfg
#  - echo  "  - 'vars/main.yml'"                    >> ansible.cfg
  - cat   ansible.cfg
  - echo  "---"                                    >  playbook.yml
  - 'echo  "- hosts: localhost"                    >> playbook.yml'
  - echo  "  roles:"                               >> playbook.yml
  - echo  "    - $(basename $(realpath .))"        >> playbook.yml
  - cat   playbook.yml
  - ansible-playbook --syntax-check --list-tasks playbook.yml
  - ansible-playbook --sudo -vvvv playbook.yml