---
language: python
python:
  - "2.7"
env:
  - TEST=00-syntax
  - TEST=01-defaults
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq realpath
 - sudo apt-get install -qq python-apt python-pycurl
install:
  - pip install ansible
  - ansible --version
script:
  - echo $PWD
  - echo  localhost > inventory
  - cd tests/$TEST && echo $PWD && echo  "[defaults]"                      >  ansible.cfg
  - cd tests/$TEST && echo $PWD && echo  "roles_path = ../../../"          >> ansible.cfg
  - cd tests/$TEST && echo $PWD && echo  "remote_user = root"              >> ansible.cfg
  - cd tests/$TEST && echo $PWD && echo  "vars_files:"                     >> ansible.cfg
  - cd tests/$TEST && echo $PWD && echo  "  - 'vars/main.yml'"             >> ansible.cfg
  - cd tests/$TEST && echo $PWD && cat   ansible.cfg
  - cd tests/$TEST && echo $PWD && echo  "---"                             >  playbook.yml
  - cd tests/$TEST && echo $PWD && echo  "- roles:"                        >> playbook.yml
  - cd tests/$TEST && echo $PWD && echo  "    - $(basename $(realpath .))" >> playbook.yml
  - cd tests/$TEST && echo $PWD && cat   playbook.yml
  - cd tests/$TEST && echo $PWD && ansible-playbook -i inventory --syntax-check --list-tasks playbook.yml

#  - ansible-playbook -i inventory --connection=local --sudo -vvvv tests/01-defaults/playbook.yml
#  - ansible-playbook -i inventory --connection=local --sudo -vvvv tests/01-defaults/validate.yml