---
language: ruby # python
rvm:
  - 2.0.0
# python:
#  - "2.7"
env:
  - TEST=00-syntax
  - TEST=01-defaults
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq realpath
 - sudo apt-get install -qq python-apt python-pycurl
install:
  - pip install ansible
  - ansible --version
script:

  - 'echo  localhost > inventory'
  - 'echo  "[defaults]"                             >  ansible.cfg'
  - 'echo  "hostfile = ./inventory"                 >> ansible.cfg'
  - 'echo  "roles_path = $(dirname $(realpath .))"  >> ansible.cfg'
  - 'echo  "remote_user = root"                     >> ansible.cfg'
  - 'echo  "transport = local"                      >> ansible.cfg'
  - 'cat   ansible.cfg'

  - 'echo  "---"                                    >  playbook.yml'
  - 'echo  "- hosts: localhost"                     >>  playbook.yml'
  - 'echo  "  roles:"                               >>  playbook.yml'
  - 'echo  "    - $(basename $(realpath .))"        >>  playbook.yml'
  - 'test ! -f tests/$TEST/vars/main.yml && return 0 || echo "  vars_files:" | tee -a playbook.yml'
  - 'test ! -f tests/$TEST/vars/main.yml && return 0 || echo "    - tests/$TEST/vars/main.yml" | tee -a playbook.yml'
  - 'cat playbook.yml'

  - ansible-playbook --syntax-check --list-tasks playbook.yml
  - ansible-playbook --sudo -vvvv playbook.yml
  - >
    ansible-playbook --sudo -vvvv playbook.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
