---
language: python
python:
  - "2.7"
env:
  - TEST=00-syntax
  - TEST=01-defaults
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq realpath
 - sudo apt-get install -qq python-apt python-pycurl
install:
  - pip install ansible
  - ansible --version
script:

  - 'echo  localhost > inventory'
  - 'echo  "[defaults]"                             >  ansible.cfg
  - 'echo  "hostfile = ./inventory"                 | tee -a !$'
  - 'echo  "roles_path = $(dirname $(realpath .))"  | tee -a !$'
  - 'echo  "remote_user = root"                     | tee -a !$'
  - 'echo  "transport = local"                      | tee -a !$'
  - 'cat   !$'

  - 'echo  "---"                                    >  playbook.yml
  - 'echo  "- hosts: localhost"                     | tee -a !$'
  - 'echo  "  roles:"                               | tee -a !$'
  - 'echo  "    - $(basename $(realpath .))"        | tee -a !$'
  - 'test ! -f tests/$TEST/vars/main.yml && return 0 || echo "    - tests/$TEST/vars/main.yml" | tee -a !$'
  - 'test ! -f tests/$TEST/vars/main.yml && return 0 || echo "    - tests/$TEST/vars/main.yml" | tee -a !$'
  - 'cat !$'

  - ansible-playbook --syntax-check --list-tasks playbook.yml
  - ansible-playbook --sudo -vvvv playbook.yml
  - >
    ansible-playbook --sudo -vvvv playbook.yml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
