---

##
## @param <string|directory> composer_file_path
##
- name: "composer:create:target:directory | Ensure target directory exists "
  file:
    state: "directory"
    path: "{{ item.directory }}"
  with_items:
    - '{ "directory": "{{ composer_file_path|dirname }}"}'
  when: '( item|default("none") != "none" )'
  sudo: "yes"