---

- name: "composer:executable:directory | Ensure executable directory exists "
  file:
    state: 'directory'
    path:  '{{ item.directory }}'
  with_items:
    - '{"directory":"{{ composer_executable_path|dirname if composer_executable_path|default(false) else "none" }}"}'
  when: 'item != "none"'
  sudo: 'yes'

