---

- name: "composer:group:apply | Set the phar archive's group ownership "
  file:
    path:  "{{item.file}}"
    group: "{{item.set_group}}"
    state: file
  with_items:
    - '{ "file": "{{ composer_phar_path }}", "set_group": "{{ composer_group_name }}" }'
  when: '( (item.file|default("none") != "none") and (item.set_group|default("none") != "none") )'
  sudo: yes